### ISSUE TITLE
Error since most recent Factorio 15 update

### ISSUE THREAD

**Issue by brehmluke** [narc0tiq/evoGUI#73] opened 2017-06-21 22:44 UTC
When I opened my save the following message started appearing once every second.
[EvoGUI|on_tick:update_gui] Error: __EvoGUI__/evoGUI.lua:101 attempt to index field 'evoGUI' (a nil value)
Everything was working great last night

**Comment by brehmluke** [comment] 2017-06-21 22:45
I read your comment on the previous report of this issue. Enjoy your night!

**Comment by dgw** [comment] 2017-06-22 03:47
I propose closing this as a duplicate of #71. Sounds like we'll get a fix ASAP anyway. :)

**Comment by narc0tiq** [comment] 2017-06-22 04:54
Indeed. I'll get to it sometime today, whenever I'm actually at a computer. Follow #71 for updates.

**Closed by narc0tiq** 2017-06-22 04:54 UTC
